-- AlterTable
ALTER TABLE "Seat" ADD COLUMN     "userId" INTEGER,
ALTER COLUMN "seatId" DROP DEFAULT;
DROP SEQUENCE "Seat_seatId_seq";

-- AddForeignKey
ALTER TABLE "Seat" ADD CONSTRAINT "Seat_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
